name = "QuantumTags"
uuid = "2406e0f5-9e5e-4424-966e-8bc9c78b228f"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez+git@bsc.es>"]
version = "0.3.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "0.5.16"
